version: 2.1 #updated to CircleCI 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.9.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: npm run generate
      - run: npm run createtiles
      - add_ssh_keys:
          fingerprints:
            - "c7:f9:19:fc:bc:1f:a2:43:9d:15:2b:3b:3d:ff:41:f2"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git config --global user.email info@code4japan.org
                git config --global user.name circleci
                git clone -b gh-pages git@github.com:codeforjapan/mapprint.git
                rm -rf mapprint/*
                cp -rf dist/* mapprint
                cd mapprint; git add .; git commit -m "From `git log --oneline origin/master -n 1`"; git push
            fi
